### ISSUE TITLE
Need some explanations...

### ISSUE THREAD

**Issue by dpineiden** [vittoriozamboni/django-groups-manager#52]
Hi.

I'm studying the module. I have some questions to understand it well.

In groups:
- There are a field 'entities', what is the meaning of that? I know I can choose 1 or more, but what is the functionaility?
- On the field 'properties', must go a json, but whit what content? Do you have an example that can clarify why exists?

On the members.

When sync with the django users, when create a member create an user. But not create a password. Son i have to go to the user form and create the other information. Or only sync with existing users?

That's all for the moment

**Comment by dpineiden** [comment]
Hi, another 'comment'
I been reading the code. It's looks like the entities have the same functionality as 'roles'. But there are not defined 'roles' by group, so if I need a list of 'roles' given a group I can't have this, only 'roles' asociated to members of a group. What if there are group with a role that doesn't have a member assigned with that yet?

**Comment by vittoriozamboni** [comment]
Hi! Apologies for the delay.

In order from the first to the second comment:

- "entities" can be used to link together different groups. For example, you can have three groups: "Company 1", "Company 2" and "Company 3". The first two can be linked to "Business Partners" and the third one to "Customers". Entities are not used anywhere else in the code, so no check is done for them. They were created to mirror the openbravo entities.
- "properties" has the sole role of allowing to load custom data, is not used anywhere else in the code. Adding this field directly in the library is my biggest regret because of the huge effort of maintaining JSON field wrapper dependencies over the years.
- this is up to you. The connection within the library is made through the membership, so that information can't be retrieved. You can either extend the Group model and associate all the possible roles, extend the Role model to associate the different groups or create a static variable (if the roles are not dynamic and can be divided into categories).

**Comment by dpineiden** [comment]
Thanks!
Now is more clear to me, is a great module but not simple to manage. But reading the code i can understand the connections :)
Best regards!
